name: Lint and Test

on:
  push:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"
      - run: pnpm i --frozen-lockfile
      - run: pnpm lint
      - run: pnpm exec playwright install
      - run: pnpm test
      - run: pnpm test:e2e
